### ISSUE TITLE
Progress

### ISSUE THREAD

**Issue by hirenshah** [jameselks/facebook-group-to-wordpress#1]
How is the work on this going?  It looks exactly like something I am interested in :)

**Comment by jameselks** [comment]
Hey @hirenshah — sorry for the delay, I didn't get the notification. It's rough, but it works. It will pull all images and video and content into individual posts in Wordpress. If you're still interested I'll try and spend some more time on it, starting with the documentation.

**Comment by jameselks** [comment]
Going to go ahead and close this one.
